<?php

namespace Database\Seeders;

use App\Models\Partner;
use App\Models\PartnerTier;
use App\Models\User;
use Illuminate\Database\Seeder;

class PartnerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get or create a test user
        $user = User::firstOrCreate(
            ['email' => 'demo@trackly.io'],
            [
                'name' => 'Demo User',
                'password' => bcrypt('password'),
                'email_verified_at' => now(),
            ]
        );

        // Get partner tiers
        $bronzeTier = PartnerTier::where('slug', 'bronze')->first();
        $silverTier = PartnerTier::where('slug', 'silver')->first();
        $goldTier = PartnerTier::where('slug', 'gold')->first();

        // Realistic Thai dive shops and tourism businesses
        $partners = [
            [
                'user_id' => $user->id,
                'partner_tier_id' => $goldTier?->id,
                'business_name' => 'Crystal Dive Koh Tao',
                'business_type' => 'dive_shop',
                'contact_name' => 'Som Chai',
                'email' => 'info@crystaldive.com',
                'phone' => '+66 77 456 100',
                'address' => '14/2 Moo 2, Sairee Beach',
                'city' => 'Koh Tao',
                'country' => 'Thailand',
                'website' => 'https://crystaldive.com',
                'commission_structure' => 'percentage',
                'default_commission_rate' => 15.00,
                'payment_method' => 'promptpay',
                'payment_currency' => 'THB',
                'promptpay_id' => '0812345678',
                'total_revenue_generated' => 485000.00,
                'total_commissions_paid' => 72750.00,
                'calculated_plv' => 125000.00,
                'engagement_score' => 85.50,
                'total_referrals' => 142,
                'successful_conversions' => 98,
                'conversion_rate' => 69.01,
                'last_referral_at' => now()->subDays(2),
                'joined_at' => now()->subMonths(8),
                'is_active' => true,
            ],
            [
                'user_id' => $user->id,
                'partner_tier_id' => $silverTier?->id,
                'business_name' => 'Big Blue Diving',
                'business_type' => 'dive_shop',
                'contact_name' => 'Nong Ploy',
                'email' => 'bookings@bigbluediving.com',
                'phone' => '+66 77 456 415',
                'address' => '32/5 Sairee Village',
                'city' => 'Koh Tao',
                'country' => 'Thailand',
                'website' => 'https://bigbluediving.com',
                'commission_structure' => 'percentage',
                'default_commission_rate' => 12.50,
                'payment_method' => 'bank_transfer',
                'payment_currency' => 'THB',
                'bank_name' => 'Bangkok Bank',
                'bank_account_number' => '123-4-56789-0',
                'bank_account_name' => 'Big Blue Diving Co., Ltd.',
                'total_revenue_generated' => 325000.00,
                'total_commissions_paid' => 40625.00,
                'calculated_plv' => 89000.00,
                'engagement_score' => 72.30,
                'total_referrals' => 87,
                'successful_conversions' => 64,
                'conversion_rate' => 73.56,
                'last_referral_at' => now()->subDays(5),
                'joined_at' => now()->subMonths(6),
                'is_active' => true,
            ],
            [
                'user_id' => $user->id,
                'partner_tier_id' => $goldTier?->id,
                'business_name' => 'Koh Tao Kite School',
                'business_type' => 'kite_school',
                'contact_name' => 'Alex Johnson',
                'email' => 'info@kohtaokite.com',
                'phone' => '+66 84 123 4567',
                'address' => 'Chalok Bay',
                'city' => 'Koh Tao',
                'country' => 'Thailand',
                'website' => 'https://kohtaokite.com',
                'commission_structure' => 'percentage',
                'default_commission_rate' => 20.00,
                'payment_method' => 'promptpay',
                'payment_currency' => 'THB',
                'promptpay_id' => '0891234567',
                'total_revenue_generated' => 420000.00,
                'total_commissions_paid' => 84000.00,
                'calculated_plv' => 110000.00,
                'engagement_score' => 88.75,
                'total_referrals' => 95,
                'successful_conversions' => 78,
                'conversion_rate' => 82.11,
                'last_referral_at' => now()->subDays(1),
                'joined_at' => now()->subMonths(10),
                'is_active' => true,
            ],
            [
                'user_id' => $user->id,
                'partner_tier_id' => $silverTier?->id,
                'business_name' => 'Sairee Hut Resort',
                'business_type' => 'hotel',
                'contact_name' => 'Khun Somying',
                'email' => 'reservations@saireehut.com',
                'phone' => '+66 77 456 289',
                'address' => '19/9 Moo 1, Sairee Beach',
                'city' => 'Koh Tao',
                'country' => 'Thailand',
                'website' => 'https://saireehut.com',
                'commission_structure' => 'percentage',
                'default_commission_rate' => 10.00,
                'payment_method' => 'bank_transfer',
                'payment_currency' => 'THB',
                'bank_name' => 'Kasikorn Bank',
                'bank_account_number' => '987-6-54321-0',
                'bank_account_name' => 'Sairee Hut Co., Ltd.',
                'total_revenue_generated' => 280000.00,
                'total_commissions_paid' => 28000.00,
                'calculated_plv' => 65000.00,
                'engagement_score' => 65.20,
                'total_referrals' => 68,
                'successful_conversions' => 52,
                'conversion_rate' => 76.47,
                'last_referral_at' => now()->subDays(7),
                'joined_at' => now()->subMonths(5),
                'is_active' => true,
            ],
            [
                'user_id' => $user->id,
                'partner_tier_id' => $bronzeTier?->id,
                'business_name' => 'Island Life Hostel',
                'business_type' => 'hostel',
                'contact_name' => 'Mike Thompson',
                'email' => 'stay@islandlifehostel.com',
                'phone' => '+66 62 345 6789',
                'address' => '45/12 Mae Haad Village',
                'city' => 'Koh Tao',
                'country' => 'Thailand',
                'website' => 'https://islandlifehostel.com',
                'commission_structure' => 'fixed',
                'default_commission_rate' => 0,
                'fixed_commission_amount' => 200.00,
                'payment_method' => 'promptpay',
                'payment_currency' => 'THB',
                'promptpay_id' => '0623456789',
                'total_revenue_generated' => 145000.00,
                'total_commissions_paid' => 9800.00,
                'calculated_plv' => 42000.00,
                'engagement_score' => 58.40,
                'total_referrals' => 49,
                'successful_conversions' => 38,
                'conversion_rate' => 77.55,
                'last_referral_at' => now()->subDays(12),
                'joined_at' => now()->subMonths(3),
                'is_active' => true,
            ],
            [
                'user_id' => $user->id,
                'partner_tier_id' => $silverTier?->id,
                'business_name' => 'Koh Tao Discovery Tours',
                'business_type' => 'tour_operator',
                'contact_name' => 'Khun Niran',
                'email' => 'tours@kohtaodiscovery.com',
                'phone' => '+66 81 987 6543',
                'address' => '78/3 Mae Haad Pier',
                'city' => 'Koh Tao',
                'country' => 'Thailand',
                'website' => 'https://kohtaodiscovery.com',
                'commission_structure' => 'percentage',
                'default_commission_rate' => 18.00,
                'payment_method' => 'bank_transfer',
                'payment_currency' => 'THB',
                'bank_name' => 'SCB (Siam Commercial Bank)',
                'bank_account_number' => '456-7-89012-3',
                'bank_account_name' => 'Koh Tao Discovery Co., Ltd.',
                'total_revenue_generated' => 195000.00,
                'total_commissions_paid' => 35100.00,
                'calculated_plv' => 58000.00,
                'engagement_score' => 70.80,
                'total_referrals' => 56,
                'successful_conversions' => 44,
                'conversion_rate' => 78.57,
                'last_referral_at' => now()->subDays(4),
                'joined_at' => now()->subMonths(4),
                'is_active' => true,
            ],
            [
                'user_id' => $user->id,
                'partner_tier_id' => $bronzeTier?->id,
                'business_name' => 'Sunset Beach Bungalows',
                'business_type' => 'hotel',
                'contact_name' => 'Khun Pranee',
                'email' => 'info@sunsetbeachbungalows.com',
                'phone' => '+66 77 456 745',
                'address' => '22/8 Sairee Beach',
                'city' => 'Koh Tao',
                'country' => 'Thailand',
                'commission_structure' => 'percentage',
                'default_commission_rate' => 8.00,
                'payment_method' => 'promptpay',
                'payment_currency' => 'THB',
                'promptpay_id' => '0774567450',
                'total_revenue_generated' => 95000.00,
                'total_commissions_paid' => 7600.00,
                'calculated_plv' => 28000.00,
                'engagement_score' => 45.60,
                'total_referrals' => 32,
                'successful_conversions' => 24,
                'conversion_rate' => 75.00,
                'last_referral_at' => now()->subDays(20),
                'joined_at' => now()->subMonths(2),
                'is_active' => true,
            ],
            [
                'user_id' => $user->id,
                'partner_tier_id' => $bronzeTier?->id,
                'business_name' => 'Ocean Breeze Transfer',
                'business_type' => 'transfer_service',
                'contact_name' => 'Khun Somchai',
                'email' => 'booking@oceanbreezetransfer.com',
                'phone' => '+66 89 765 4321',
                'address' => '5/2 Lomprayah Pier',
                'city' => 'Koh Tao',
                'country' => 'Thailand',
                'commission_structure' => 'percentage',
                'default_commission_rate' => 25.00,
                'payment_method' => 'promptpay',
                'payment_currency' => 'THB',
                'promptpay_id' => '0897654321',
                'total_revenue_generated' => 68000.00,
                'total_commissions_paid' => 17000.00,
                'calculated_plv' => 35000.00,
                'engagement_score' => 52.30,
                'total_referrals' => 28,
                'successful_conversions' => 22,
                'conversion_rate' => 78.57,
                'last_referral_at' => now()->subDays(15),
                'joined_at' => now()->subMonth(),
                'is_active' => true,
            ],
        ];

        foreach ($partners as $partnerData) {
            Partner::create($partnerData);
        }

        $this->command->info('Created ' . count($partners) . ' realistic Thai tourism partners!');
    }
}
