<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Partner extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'user_id',
        'partner_tier_id',
        'business_name',
        'business_type',
        'contact_name',
        'email',
        'phone',
        'address',
        'city',
        'country',
        'website',
        'commission_structure',
        'default_commission_rate',
        'fixed_commission_amount',
        'tiered_commission_rules',
        'payment_method',
        'payment_currency',
        'stripe_account_id',
        'promptpay_id',
        'bank_name',
        'bank_account_number',
        'bank_account_name',
        'total_revenue_generated',
        'total_commissions_paid',
        'calculated_plv',
        'engagement_score',
        'total_referrals',
        'successful_conversions',
        'conversion_rate',
        'last_referral_at',
        'joined_at',
        'is_active',
        'notes',
        'metadata',
    ];

    protected $casts = [
        'tiered_commission_rules' => 'array',
        'metadata' => 'array',
        'default_commission_rate' => 'decimal:2',
        'fixed_commission_amount' => 'decimal:2',
        'total_revenue_generated' => 'decimal:2',
        'total_commissions_paid' => 'decimal:2',
        'calculated_plv' => 'decimal:2',
        'engagement_score' => 'decimal:2',
        'conversion_rate' => 'decimal:2',
        'total_referrals' => 'integer',
        'successful_conversions' => 'integer',
        'is_active' => 'boolean',
        'last_referral_at' => 'datetime',
        'joined_at' => 'datetime',
    ];

    /**
     * Relationships
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function tier(): BelongsTo
    {
        return $this->belongsTo(PartnerTier::class, 'partner_tier_id');
    }

    public function trackingLinks(): HasMany
    {
        return $this->hasMany(TrackingLink::class);
    }

    public function bookings(): HasMany
    {
        return $this->hasMany(Booking::class);
    }

    public function commissions(): HasMany
    {
        return $this->hasMany(Commission::class);
    }

    public function referralsSent(): HasMany
    {
        return $this->hasMany(Referral::class, 'referring_partner_id');
    }

    public function referralsReceived(): HasMany
    {
        return $this->hasMany(Referral::class, 'receiving_partner_id');
    }

    /**
     * Calculate Average Revenue Per Partner (ARPP)
     * This is the annual revenue generated by this partner
     */
    public function calculateARPP(): float
    {
        $completedBookings = $this->bookings()
            ->where('status', 'completed')
            ->whereYear('completed_at', now()->year)
            ->sum('amount');

        return (float) $completedBookings;
    }

    /**
     * Calculate Partner Churn Rate
     * Percentage likelihood of partner becoming inactive
     */
    public function calculateChurnRate(): float
    {
        // If partner hasn't made a referral in 90 days, increase churn risk
        if (!$this->last_referral_at) {
            return 50.0;
        }

        $daysSinceLastReferral = abs(now()->diffInDays($this->last_referral_at));

        if ($daysSinceLastReferral > 180) {
            return 80.0;
        } elseif ($daysSinceLastReferral > 90) {
            return 50.0;
        } elseif ($daysSinceLastReferral > 30) {
            return 20.0;
        }

        return 5.0;
    }

    /**
     * Calculate Average Partner Lifespan (APL)
     * APL = 1 / Churn Rate (as decimal)
     */
    public function calculateAPL(): float
    {
        $churnRate = $this->calculateChurnRate();

        if ($churnRate == 0) {
            return 10.0; // Max lifespan estimate
        }

        return 1 / ($churnRate / 100);
    }

    /**
     * Calculate Partnership Costs
     * Annual costs associated with maintaining this partnership
     */
    public function calculatePartnershipCosts(): float
    {
        // Base administrative cost per partner per year
        $baseCost = 500; // THB or USD depending on currency

        // Commission costs (already paid)
        $commissionCosts = $this->commissions()
            ->whereYear('paid_at', now()->year)
            ->sum('amount');

        return $baseCost + (float) $commissionCosts;
    }

    /**
     * Calculate Partner Lifetime Value (PLV)
     * PLV = (ARPP - Partnership Costs) × APL
     */
    public function calculatePLV(): float
    {
        $arpp = $this->calculateARPP();
        $costs = $this->calculatePartnershipCosts();
        $apl = $this->calculateAPL();

        $plv = ($arpp - $costs) * $apl;

        // Update cached PLV
        $this->update(['calculated_plv' => $plv]);

        return $plv;
    }

    /**
     * Update engagement score based on partner activity
     */
    public function updateEngagementScore(): void
    {
        $score = 0;

        // Recent activity (30 points)
        if ($this->last_referral_at && $this->last_referral_at->isAfter(now()->subDays(7))) {
            $score += 30;
        } elseif ($this->last_referral_at && $this->last_referral_at->isAfter(now()->subDays(30))) {
            $score += 20;
        } elseif ($this->last_referral_at && $this->last_referral_at->isAfter(now()->subDays(90))) {
            $score += 10;
        }

        // Conversion rate (30 points)
        $score += min(30, $this->conversion_rate * 3);

        // Total referrals volume (20 points)
        if ($this->total_referrals > 100) {
            $score += 20;
        } elseif ($this->total_referrals > 50) {
            $score += 15;
        } elseif ($this->total_referrals > 10) {
            $score += 10;
        } elseif ($this->total_referrals > 0) {
            $score += 5;
        }

        // User account activity (20 points)
        if ($this->user && $this->user->last_login_at) {
            if ($this->user->last_login_at->isAfter(now()->subDays(7))) {
                $score += 20;
            } elseif ($this->user->last_login_at->isAfter(now()->subDays(30))) {
                $score += 10;
            }
        }

        $this->update(['engagement_score' => $score]);
    }

    /**
     * Update conversion rate
     */
    public function updateConversionRate(): void
    {
        if ($this->total_referrals > 0) {
            $rate = ($this->successful_conversions / $this->total_referrals) * 100;
            $this->update(['conversion_rate' => $rate]);
        }
    }

    /**
     * Scopes
     */
    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }

    public function scopeByTier($query, $tierSlug)
    {
        return $query->whereHas('tier', function ($q) use ($tierSlug) {
            $q->where('slug', $tierSlug);
        });
    }

    public function scopeTopPerformers($query, $limit = 10)
    {
        return $query->active()
            ->orderBy('calculated_plv', 'desc')
            ->limit($limit);
    }

    public function scopeAtRisk($query)
    {
        return $query->active()
            ->where('last_referral_at', '<', now()->subDays(90))
            ->orWhere('engagement_score', '<', 30);
    }
}
